### ISSUE TITLE
Extend license requirements to other units

### ISSUE THREAD

**Issue by bonnee** [eagletrt/c-template#3]
Specifying a "pint" of beer can be restricting if an appropriate measuring tool cannot be found. It can be better to not specify a particular unit, but I'm not sure on how to phrase it

**Comment by notfilippo** [comment]
In my opinion, the definition of a "pint" fits perfectly with the spirit of the license. Offering a "pint" to the copyright holder(s) is a sign of gratitude, which similarly to a donation, can come in many sizes – not always proportional to the appreciation of the work done by the copyright holder(s).
